#This is to setup one controller and two broker

services:
  # Kafka Controller Node
  kafka-controller:
    image: apache/kafka:latest
    container_name: kafka-controller
    ports:
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller:9093
      KAFKA_LISTENERS: CONTROLLER://kafka-controller:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kafka/logs
      KAFKA_CLUSTER_ID: 5L6g3nShT-eMCtK--X86sw
    volumes:
      - /home/spirit/kafka/controller-data

  # Kafka Broker 1
  kafka-broker-1:
    image: apache/kafka:latest
    container_name: kafka-broker-1
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller:9093
      KAFKA_LISTENERS: BROKER://kafka-broker-1:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kafka/logs
      KAFKA_CLUSTER_ID: 5L6g3nShT-eMCtK--X86sw
    depends_on:
      - kafka-controller
    volumes:
      - /home/spirit/kafka/broker1-data

  # Kafka Broker 2
  kafka-broker-2:
    image: apache/kafka:latest
    container_name: kafka-broker-2
    ports:
      - "9095:9095"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller:9093
      KAFKA_LISTENERS: BROKER://kafka-broker-2:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kafka/logs
      KAFKA_CLUSTER_ID: 5L6g3nShT-eMCtK--X86sw
    depends_on:
      - kafka-controller
    volumes:
      - /home/spirit/kafka/broker2-data

 # Kafka Broker 3
  kafka-broker-3:
    image: apache/kafka:latest
    container_name: kafka-broker-3
    ports:
      - "9096:9096"
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller:9093
      KAFKA_LISTENERS: BROKER://kafka-broker-3:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kafka/logs
      KAFKA_CLUSTER_ID: 5L6g3nShT-eMCtK--X86sw
    depends_on:
      - kafka-controller
    volumes:
      - /home/spirit/kafka/broker3-data

# volumes:
#   /home/spirit/kafkacontroller-data:
#   /home/spirit/kafkabroker1-data:
#   /home/spirit/kafka/broker2-data:





#XzkT43J1T6TcwNTJENDM2Qk

# version: '3.8'

# services:
#   # Kafka Controller
#   kafka-controller:
#     image: apache/kafka:latest
#     container_name: kafka-controller
#     environment:
#       KAFKA_NODE_ID: 1
#       KAFKA_PROCESS_ROLES: controller
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller:9093
#       KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9093
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
#       KAFKA_LOG_DIRS: /var/lib/kafka/data
#       KAFKA_CLUSTER_ID: my-cluster-id
#     volumes:
#       - /tmp/controller-data:/var/lib/kafka/data
#     ports:
#       - "9093:9093" # Port for Controller communication

#   # Kafka Broker 1
#   kafka1:
#     image: apache/kafka:latest
#     container_name: kafka1
#     environment:
#       KAFKA_NODE_ID: 2
#       KAFKA_PROCESS_ROLES: broker
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller:9093
#       KAFKA_LISTENERS: BROKER://0.0.0.0:9094,OUTSIDE://0.0.0.0:9091
#       KAFKA_ADVERTISED_LISTENERS: BROKER://kafka1:9094,OUTSIDE://localhost:9091
#       KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,OUTSIDE:PLAINTEXT
#       KAFKA_LOG_DIRS: /var/lib/kafka/data
#       KAFKA_CLUSTER_ID: my-cluster-id
#     volumes:
#       - /tmp/broker1-data:/var/lib/kafka/data
#     ports:
#       # - "9091:9091" # External port for Kafka Broker 1
#       - "9094:9094" # Internal port for Kafka Broker 1
#     depends_on:
#       - kafka-controller

#   # Kafka Broker 2
#   kafka2:
#     image: apache/kafka:latest
#     container_name: kafka2
#     environment:
#       KAFKA_NODE_ID: 3
#       KAFKA_PROCESS_ROLES: broker
#       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller:9093
#       KAFKA_LISTENERS: BROKER://0.0.0.0:9094,OUTSIDE://0.0.0.0:9092
#       KAFKA_ADVERTISED_LISTENERS: BROKER://kafka2:9094,OUTSIDE://localhost:9092
#       KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,OUTSIDE:PLAINTEXT
#       KAFKA_LOG_DIRS: /var/lib/kafka/data
#       KAFKA_CLUSTER_ID: my-cluster-id
#     volumes:
#       - /tmp/broker2-data:/var/lib/kafka/data
#     ports:
#       # - "9092:9092" # External port for Kafka Broker 2
#       - "9095:9095" # Internal port for Kafka Broker 2
#     depends_on:
#       - kafka-controller

# volumes:
#   controller-data:
#   broker1-data:
#   broker2-data:








# version: '3'

# services:
#   # Kafka Broker 1
#   kafka1:
#     image: apache/kafka:latest
#     container_name: kafka1
#     environment:
#       KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
#       KAFKA_LISTENER_NAME: INSIDE
#       KAFKA_LISTENER_PORT: 9093
#       KAFKA_LISTENER_INTERNAL: INSIDE
#       KAFKA_LISTENER_EXTERNAL: OUTSIDE
#       KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9093,OUTSIDE://localhost:9091
#       KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
#       KAFKA_LOG_DIRS: /var/lib/kafka/data
#       KAFKA_KRAFT_MODE: "true"
#       KAFKA_PROCESS_ROLES: broker,controller
#       KAFKA_LISTENER_NAME_OUTSIDE: OUTSIDE
#       KAFKA_LISTENER_PORT_OUTSIDE: 9091
#       KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9091
#       KAFKA_PORT: 9093
#       KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
#       KAFKA_LOG_RETENTION_HOURS: 168
#       KAFKA_LOG_SEGMENT_BYTES: 1073741824
#       KAFKA_ZOOKEEPER_CONNECT: ""
#     volumes:
#       - /tmp/broker1-data:/var/lib/kafka/data
#     ports:
#       - "9091:9091"  # External port for Kafka Broker 1
#       - "9093:9093"  # Internal port for Kafka Broker 1

#   # Kafka Broker 2
#   kafka2:
#     image: apache/kafka:latest
#     container_name: kafka2
#     environment:
#       KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
#       KAFKA_LISTENER_NAME: INSIDE
#       KAFKA_LISTENER_PORT: 9093
#       KAFKA_LISTENER_INTERNAL: INSIDE
#       KAFKA_LISTENER_EXTERNAL: OUTSIDE
#       KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:9093,OUTSIDE://localhost:9092
#       KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
#       KAFKA_LOG_DIRS: /var/lib/kafka/data
#       KAFKA_KRAFT_MODE: "true"
#       KAFKA_PROCESS_ROLES: broker,controller
#       KAFKA_LISTENER_NAME_OUTSIDE: OUTSIDE
#       KAFKA_LISTENER_PORT_OUTSIDE: 9092
#       KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
#       KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:9093,OUTSIDE://localhost:9092
#       KAFKA_PORT: 9093
#       KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
#       KAFKA_LOG_RETENTION_HOURS: 168
#       KAFKA_LOG_SEGMENT_BYTES: 1073741824
#       KAFKA_ZOOKEEPER_CONNECT: ""
#     volumes:
#       - /tmp/broker2-data:/var/lib/kafka/data
#     ports:
#       - "9092:9092"  # External port for Kafka Broker 2
#       - "9093:9093"  # Internal port for Kafka Broker 2

#   # Kafka Broker 3
#   kafka3:
#     image: apache/kafka:latest
#     container_name: kafka3
#     environment:
#       KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
#       KAFKA_LISTENER_NAME: INSIDE
#       KAFKA_LISTENER_PORT: 9093
#       KAFKA_LISTENER_INTERNAL: INSIDE
#       KAFKA_LISTENER_EXTERNAL: OUTSIDE
#       KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:9093,OUTSIDE://localhost:9093
#       KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
#       KAFKA_LOG_DIRS: /var/lib/kafka/data
#       KAFKA_KRAFT_MODE: "true"
#       KAFKA_PROCESS_ROLES: broker,controller
#       KAFKA_LISTENER_NAME_OUTSIDE: OUTSIDE
#       KAFKA_LISTENER_PORT_OUTSIDE: 9093
#       KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9093
#       KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:9093,OUTSIDE://localhost:9093
#       KAFKA_PORT: 9093
#       KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
#       KAFKA_LOG_RETENTION_HOURS: 168
#       KAFKA_LOG_SEGMENT_BYTES: 1073741824
#       KAFKA_ZOOKEEPER_CONNECT: ""
#     volumes:
#       - /tmp/broker3-data:/var/lib/kafka/data
#     ports:
#       - "9093:9093"  # External port for Kafka Broker 3
#       - "9094:9094"  # Internal port for Kafka Broker 3

# networks:
#   default:
#     driver: bridge
